"""add_run_number_unique_constraint

Revision ID: 10534fb2e8d2
Revises: abf189cdd018
Create Date: 2026-06-21 04:34:51.697974
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '10534fb2e8d2'
down_revision: Union[str, None] = 'abf189cdd018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_runs_profile_location_number', 'runs', ['profile_id', 'location', 'run_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_runs_profile_location_number', table_name='runs')
    # ### end Alembic commands ###
