"""initial_schema

Revision ID: abf189cdd018
Revises: 
Create Date: 2026-06-21 04:05:49.779671
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'abf189cdd018'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('BASE', 'MAGIC_RARE', 'CHARM', 'JEWEL', 'SET', 'UNIQUE', 'RUNEWORD', 'RUNE', 'CONSUMABLE', name='itemcategory'), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_rotw', sa.Boolean(), nullable=False),
    sa.Column('is_ladder_only', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('game_mode', sa.Enum('LADDER', 'NON_LADDER', 'HARDCORE', 'HARDCORE_LADDER', name='gamemode'), nullable=False),
    sa.Column('character_class', sa.Enum('AMAZON', 'NECROMANCER', 'BARBARIAN', 'SORCERESS', 'PALADIN', 'DRUID', 'ASSASSIN', 'WARLOCK', name='characterclass'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Enum('ANDARIEL', 'COUNTESS', 'PIT', 'COWS', 'STONY_TOMBS', 'ARCANE_SANCTUARY', 'ANCIENT_TUNNELS', 'LOWER_KURAST', 'TRAVINCAL', 'MEPHISTO', 'CHAOS_SANCTUARY', 'ELDRITCH_SHENK', 'PINDLESKIN', 'WORLDSTONE_KEEP', 'TERROR_ZONE', 'COLOSSAL_ANCIENTS', name='location'), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('terror_zone_note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_profile_location', 'runs', ['profile_id', 'location'], unique=False)
    op.create_table('run_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_items')
    op.drop_index('ix_runs_profile_location', table_name='runs')
    op.drop_table('runs')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
